### ISSUE TITLE
Parts of source going everywhere excepted in one rectangle

### ISSUE THREAD

**Issue by N1coc4colA** [alex47/Dual-Kawase-Blur#3]
Hi, I tried this project when I was on Qt 5.7.x and 5.9.x. Now I'm using Qt 5.15.x and it seems that in the newer version there's an issue with the shaders/fragments. I'm using OpenGL 4.6. When I use any image, I get a bottom left square well rendered. But otherwise, all the image is a mix of some little parts of the image or there's simply nothing, you can take a look at the images I attached. I'm trying to use OpenGL with Qt, so I'm new and don't see from where it could come from. I tried 1.0, 1.1 and master, all does the same result, just that 1.0 (seems to) make(s) something with more frags than the 1.1...

Files:
![v1 1](https://user-images.githubusercontent.com/50690360/119433301-e0b51b80-bcb5-11eb-9f85-632b749e6645.jpg)
![v1 0](https://user-images.githubusercontent.com/50690360/119433310-e6aafc80-bcb5-11eb-8073-401819c1a984.jpg)

**Comment by alex47** [comment]
I tried it just now with Qt 5.15.2 without any issues on my Nvidia GTX 980

What do you mean you are using OpenGL 4.6? The shaders are set to OpenGL 3.3

![image](https://user-images.githubusercontent.com/10761683/119548051-192c2680-bd96-11eb-9cc9-c2bdcf5586a7.png)

**Comment by N1coc4colA** [comment]
Oh, ok then I see, I'm still using OpenGL 4.6, but I looked into the GL files and did not find where the issue comes from...

**Comment by alex47** [comment]
Are you using linux? If yes which distro?
What video card do you have? What gpu driver?

**Comment by N1coc4colA** [comment]
I'm using Linux Deepin, based on Debian 10.8. My GPU is NVIDIA Corporation GP108M [GeForce MX250], and the driver is Bumblebee 3.2.1-20, I tried with my distro's open source driver too, but each gives the same...

**Comment by alex47** [comment]
I can reproduce this on deepin and on latest ubuntu in a vm too.
On fedora it's even worse.

I tried it on ubuntu with an AMD gpu and it is the same as in your posts.

Maybe it's a linux thing?

**Comment by N1coc4colA** [comment]
I'm using NVidia, so I guess that's about a compatibility layer but I asked my distro's maintianers if they can check it out to fix it or do something about it. But I notice that it is on Debian based and maybe on debian too...

**Comment by alex47** [comment]
I opened a bug report on Qt site: https://bugreports.qt.io/browse/QTBUG-94096

**Comment by alex47** [comment]
@N1coc4colA  I updated the project.
Please download from master and try it again.

**Comment by N1coc4colA** [comment]
Thank you, it works perfectly now :) Now I'll take care of the viewport, I did not know such things
